apiVersion: k3d.io/v1alpha2
kind: Simple
name: myk3dCluster
servers: 1
agents: 2
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
image: rancher/k3s:v1.22.2-k3s1
volumes:
  - volume: /tmp:/tmp/somepath
    nodeFilters:
      - all
ports:
  - port: 8081:80
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:8443:443
    nodeFilters:
      - loadbalancer
env:
  - envVar: a=10
    nodeFilters:
      - all
options:
  k3d:
    wait: true
    timeout: 6m0s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    gpuRequest: ""
    serversMemory: ""
    agentsMemory: ""
    labels:
    - label: app-coit-simple
      nodeFilters:
      - server:0
